BF Making > test-for-real-for-real@0.0.0 test C:\code\test-for-real-for-real > ng test --watch=false
14 07 2020 17:47:44.715:INFO [karma-server]: Karma v5.0.9 server started at http://0.0.0.0:9876/
14 07 2020 17:47:44.718:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
14 07 2020 17:47:44.722:INFO [launcher]: Starting browser Chrome
14 07 2020 17:47:47.234:INFO [Chrome 83.0.4103.116 (Windows 10)]: Connected on socket ZHQtOPEuNO7KBqzYAAAA with id 16042063
Chrome 83.0.4103.116 (Windows 10): Executed 0 of 4[32m SUCCESS[39m (0 secs / 0 secs)
[1A[2KERROR: [36m''app-lorem-picsum' is not a known element:
1. If 'app-lorem-picsum' is an Angular component, then verify that it is part of this module.
2. If 'app-lorem-picsum' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'[39m
Chrome 83.0.4103.116 (Windows 10): Executed 0 of 4[32m SUCCESS[39m (0 secs / 0 secs)
ERROR: ''app-lorem-picsum' is not a known element:
1. If 'app-lorem-picsum' is an Angular component, then verify that it is part of this module.
2. If 'app-lorem-picsum' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
[1A[2KERROR: [36m''app-lorem-picsum' is not a known element:
1. If 'app-lorem-picsum' is an Angular component, then verify that it is part of this module.
2. If 'app-lorem-picsum' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'[39m
Chrome 83.0.4103.116 (Windows 10): Executed 0 of 4[32m SUCCESS[39m (0 secs / 0 secs)
ERROR: ''app-lorem-picsum' is not a known element:
1. If 'app-lorem-picsum' is an Angular component, then verify that it is part of this module.
2. If 'app-lorem-picsum' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
[1A[2KERROR: [36m''app-lorem-picsum' is not a known element:
1. If 'app-lorem-picsum' is an Angular component, then verify that it is part of this module.
2. If 'app-lorem-picsum' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'[39m
Chrome 83.0.4103.116 (Windows 10): Executed 0 of 4[32m SUCCESS[39m (0 secs / 0 secs)
ERROR: ''app-lorem-picsum' is not a known element:
1. If 'app-lorem-picsum' is an Angular component, then verify that it is part of this module.
2. If 'app-lorem-picsum' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
[1A[2K[31mChrome 83.0.4103.116 (Windows 10) AppComponent should render title FAILED[39m
	TypeError: Cannot read property 'textContent' of null
	    at <Jasmine>
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:29:51)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
	    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
	    at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:123:1)
	    at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:545:1)
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:560:1)
	    at <Jasmine>
Chrome 83.0.4103.116 (Windows 10): Executed 1 of 4[31m (1 FAILED)[39m (0 secs / 0.079 secs)
Chrome 83.0.4103.116 (Windows 10) AppComponent should render title FAILED
	TypeError: Cannot read property 'textContent' of null
	    at <Jasmine>
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:29:51)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
	    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
	    at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:123:1)
	    at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:545:1)
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:560:1)
	    at <Jasmine>
[1A[2KChrome 83.0.4103.116 (Windows 10): Executed 2 of 4[31m (1 FAILED)[39m (0 secs / 0.085 secs)
[1A[2KChrome 83.0.4103.116 (Windows 10): Executed 3 of 4[31m (1 FAILED)[39m (0 secs / 0.089 secs)
[1A[2KERROR: [36m'Can't bind to 'ngModel' since it isn't a known property of 'select'.'[39m
Chrome 83.0.4103.116 (Windows 10): Executed 3 of 4[31m (1 FAILED)[39m (0 secs / 0.089 secs)
ERROR: 'Can't bind to 'ngModel' since it isn't a known property of 'select'.'
[1A[2KERROR: [36m'Can't bind to 'ngModel' since it isn't a known property of 'select'.'[39m
Chrome 83.0.4103.116 (Windows 10): Executed 3 of 4[31m (1 FAILED)[39m (0 secs / 0.089 secs)
ERROR: 'Can't bind to 'ngModel' since it isn't a known property of 'select'.'
[1A[2KChrome 83.0.4103.116 (Windows 10): Executed 4 of 4[31m (1 FAILED)[39m (0 secs / 0.106 secs)
[1A[2KChrome 83.0.4103.116 (Windows 10): Executed 4 of 4[31m (1 FAILED)[39m (0.131 secs / 0.106 secs)
[31mTOTAL: 1 FAILED, 3 SUCCESS[39m
TOTAL: 1 FAILED, 3 SUCCESS exit by default by turning watch off in the command